### ISSUE TITLE
ERC20-BTC example, Bitcoind trouble

### ISSUE THREAD

**Issue by da-kami** [comit-network/create-comit-app#170] opened 2019-11-11 00:19 UTC
## Problem

Happened only when environment was sitting around for very long time. Probably not that relevant.

```
yarn run v1.19.1
warning ../../package.json: No license field
$ DOTENV_CONFIG_PATH=$HOME/.create-comit-app/env ts-node -r dotenv/config ./src/index.ts
Maker Ethereum address:  0xae3f86103D9014B4263D06E8DaDa84c767c9Cb1f
Taker Ethereum address:  0x7F8A3eBa837777083155654b722a1C2D26ef92Eb
Maker Bitcoin balance: 9. Erc20 Token balance: 110
Taker Bitcoin balance: 10. Erc20 Token balance: 90
Swap started! Swapping 10 tokens @ contract address 0x62d69f6867a0a084c6d313943dc22023bc263691 for 1 bitcoin
Continue?
ERC20 contract deployed! TXID:  0x1a2f6fa16ade3800c9602e7af536698170c48a0010cfa93d7d73bc3cab36fde7
Continue?
ERC20 contract funded! TXID:  0x1967cecd6db7c57b46fe57bcaf58284df80df55aaeef57b9e33d05685a461b9e
Continue?
[warning] (wallet) Handling conflicting tx: 4cc8af7e4428a00653d8ac7197567276d2199e89b8085e9e7037a4e05f0c6fb1.
[warning] (wallet) Removed conflict: 4cc8af7e4428a00653d8ac7197567276d2199e89b8085e9e7037a4e05f0c6fb1.
Bitcoin contract funded! TXID:  4cc8af7e4428a00653d8ac7197567276d2199e89b8085e9e7037a4e05f0c6fb1
Continue?
(node:17301) UnhandledPromiseRejectionWarning: Timed out in 10000ms.
(node:17301) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:17301) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by D4nte** [comment] 2019-11-11 22:58
This is a dupe of comit-network/comit-js-sdk#23

**Closed by D4nte** 2019-11-11 22:58 UTC
Labels: bug
