### ISSUE TITLE
Publish on npm as part of release github action

### ISSUE THREAD

**Issue by D4nte** [comit-network/create-comit-app#198] opened 2019-11-20 04:28 UTC
## Problem

When releasing GitHub Action, npm publication is not done.

## Goal

Avoid manual actions when releasing

## Recommendation

Do it.

**Comment by thomaseizinger** [comment] 2019-11-26 03:57
Duplicate of https://github.com/comit-network/create-comit-app/issues/104.

I'll close this one and add the other one to the epic.

**Closed by thomaseizinger** 2019-11-26 03:57 UTC
